executor: "CeleryExecutor"
webserverSecretKey: QVJabjdQZ3lLdW9JaUF5N2MxSWZGMjNaYjZ0T21mRU8=%

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

images:
  airflow:
    repository: jonathanpinzon/ucm_tfm
    tag: airflow_latest
    pullPolicy: Always

# Services Configuration
apiServer:
  replicas: 1
  args: ["bash", "-c", "exec airflow api-server --workers 2"]
  waitForMigrations:
    enabled: false
scheduler:
  replicas: 1
  waitForMigrations:
    enabled: false
statsd:
  enabled: false
ingress:
  web:
    enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/UCMTFM/ucm_tfm.git
    branch: main
    subPath: "airflow/dags"
  persistence:
    enabled: false # Do not persist DAGs (assume GitSync or baked-in)
