# Airflow executor
# One or multiple of: LocalExecutor, CeleryExecutor, KubernetesExecutor
executor: LocalExecutor
# Component Replica Counts
webserver:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
workers:
  replicas: 1

# Disabling Auxiliary Services
postgresql:
  enabled: true
redis:
  enabled: false # Not needed with LocalExecutor
flower:
  enabled: false # Not needed with LocalExecutor
statsd:
  enabled: true
ingress:
  web:
    enabled: false
  flower:
    enabled: false

# Persistence Configuration (for ephemeral data)
logs:
  persistence:
    enabled: false # Do not persist logs
dags:
  persistence:
    enabled: false # Do not persist DAGs (assume GitSync or baked-in)
